[package]
name = "phpass"
version = "0.1.0"
authors = ["Joshua Koudys <jkoudys@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
md5 = "0.7.0"
base64 = "0.12.3"
